version: '3.8'

services:
  # gateway_service:
  #   build:
  #     context: ./services/gateway
  #   container_name: gateway_service
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - redis
  #     - elasticsearch
  #     - prometheus
  #     - app

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.5.0
  #   container_name: logstash
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.5.0
  #   container_name: kibana
  #   ports:
  #     - "5601:5601"

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  # app:
  #   build:
  #     context: ./app
  #   container_name: app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - redis
  #     - rabbitmq
  #     - elasticsearch
  #     - prometheus

  # domain_service:
  #   build:
  #     context: ./services/crud
  #   container_name: domain_service
  #   ports:
  #     - "50051:50051"
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  # elastic_data:
  # prometheus_data:
  postgres_data: